# Generated by Django 4.2.7 on 2025-04-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3personelveriler',
            name='lunchbox',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
