# Generated by Django 5.1.6 on 2025-04-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_sistemayarlari_t3personelveriler_coffee_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3personelatama',
            name='coffee_break',
            field=models.BooleanField(default=False),
        ),
    ]
